# Default state for all rules
default: true

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md013.md
MD013:
  # Include tables
  tables: false
  # Include code blocks
  code_blocks: false
