# CSpell Settings
# language - current active spelling language
language: "en"
# words - list of words to be always considered correct
words:
  - "devenv"
  - "landure"
  - "taskfile"
  - "taskfiles"
  - "nixpkgs"
  - "pkgs"
  - "attrset"
  - "cachix"
# flagWords - list of words to be always considered incorrect
# This is useful for offensive words and common spelling errors.
# For example "hte" should be "the"
flagWords: []
import:
  - '@cspell/dict-en_us/cspell-ext.json'
  - '@cspell/dict-en-common-misspellings/cspell-ext.json'
  - '@cspell/dict-companies/cspell-ext.json'
  - '@cspell/dict-software-terms/cspell-ext.json'
  - '@cspell/dict-markdown/cspell-ext.json'
  - '@cspell/dict-public-licenses/cspell-ext.json'
  - '@cspell/dict-git/cspell-ext.json'
languageSettings:
  - languageId: md
    dictionaries:
      - en_us
      - companies
      - softwareTerms
      - networking-terms
      - web-services
      - computing-acronyms
      - markdown
      - public-licenses
      - git
      - en-us-common-misspellings
      - en-common-misspellings

