{ lib, ... }:
lib.types.oneOf [
  # String command
  lib.types.str
  lib.types.listOf
  lib.types.str

  lib.types.submodule
  {
    options = {
      cmds = lib.mkOption {
        type = lib.types.listOf (import ./cmd.nix) {inherit lib;};
        description = "A list of commands to be executed.";
        default = [ ];
      };

      cmd = lib.mkOption {
        type = lib.types.nullOr (import ./cmd.nix) {inherit lib;};
        description = "The command to be executed.";
        default = null;
      };

      deps = lib.mkOption {
        type = lib.types.listOf (import ./deps.nix) {inherit lib;};
        description = "Task dependencies";
        default = [ ];
      };

      desc = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        description = "Short description shown in `--list`";
        default = null;
      };

      summary = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        description = "Detailed description shown in `--summary`";
        default = null;
      };

      prompt = lib.mkOption {
        type = lib.types.oneOf [
          lib.types.str
          lib.types.listOf
          lib.types.str
        ];
        description = "Prompts shown before task execution";
        default = [ ];
      };

      aliases = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        description = "Alternative names for the task";
        default = [ ];
      };

      sources = lib.mkOption {
        type = lib.types.listOf lib.types.oneof [
          lib.types.str
          lib.types.submodule
          {
            options = {
              exclude = lib.mkOption { type = lib.types.str; };
            };
          }
        ];
        description = "A list of sources to check before running this task. Relevant for `checksum` and `timestamp` methods. Can be file paths or star globs.";
        default = [ ];
      };

      generates = lib.mkOption {
        type = lib.types.listOf lib.types.oneof [
          lib.types.str
          lib.types.submodule
          {
            options = {
              exclude = lib.mkOption { type = lib.types.str; };
            };
          }
        ];
        description = "A list of files meant to be generated by this task. Relevant for `timestamp` method. Can be file paths or star globs.";
        default = [ ];
      };

      status = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        description = "A list of commands to check if this task should run. The task is skipped otherwise. This overrides `method`, `sources` and `generates`.";
        default = [ ];
      };

      preconditions = lib.mkOption {
        type = lib.types.listOf (import ./precondition.nix) {inherit lib;};
        description = "A list of commands to check if this task should run. If a condition is not met, the task will error.";
        default = [ ];
      };

      dir = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        description = "The directory in which this task should run. Defaults to the current working directory.";
        default = null;
      };

      set = lib.mkOption {
        type = lib.types.nullOr (import ./shell-set.nix) {inherit lib;};
        description = "Enables POSIX shell options for all of a task's commands. See https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html";
        default = null;
      };

      shopt = lib.mkOption {
        type = lib.types.nullOr (import ./shell-shopt.nix) {inherit lib;};
        description = "Enables Bash shell options for all of a task's commands. See https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html";
        default = null;
      };

      vars = lib.mkOption {
        type = lib.types.attrsOf (import ./variable.nix) {inherit lib;};
        description = "A set of variables that can be used in the task";
        default = { };
      };

      env = lib.mkOption {
        type = lib.types.attrsOf (import ./variable.nix) {inherit lib;};
        description = "A set of environment variables that will be made available to shell commands.";
        default = { };
      };

      dotenv = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        description = "A list of `.env` file paths to be parsed.";
        default = [ ];
      };

      silent = lib.mkOption {
        type = lib.types.nullOr lib.types.bool;
        description = "Hides task name and command from output. The command's output will still be redirected to `STDOUT` and `STDERR`. When combined with the `--list` flag, task descriptions will be hidden.";
        defaultText = "false";
        default = null;
      };

      interactive = lib.mkOption {
        type = lib.types.nullOr lib.types.bool;
        description = "Tells task that the command is interactive.";
        defaultText = "false";
        default = null;
      };

      internal = lib.mkOption {
        type = lib.types.nullOr lib.types.bool;
        description = "Stops a task from being callable on the command line. It will also be omitted from the output when used with `--list`.";
        defaultText = "false";
        default = null;
      };

      method = lib.mkOption {
        type = lib.types.nullOr (
          lib.types.enum [
            "checksum"
            "timestamp"
            "none"
          ]
        );
        description = "Defines which method is used to check the task is up-to-date. `timestamp` will compare the timestamp of the sources and generates files. `checksum` will check the checksum (You probably want to ignore the .task folder in your .gitignore file). `none` skips any validation and always run the task.";
        defaultText = "none";
        default = null;
      };

      prefix = lib.mkOption {
        type = lib.types.nullOr lib.types.string;
        description = "Defines a string to prefix the output of tasks running in parallel. Only used when the output mode is `prefixed`.";
        default = null;

      };

      ignore_error = lib.mkOption {
        type = lib.types.nullOr lib.types.bool;
        description = "Continue execution if errors happen while executing commands.";
        defaultText = "false";
        default = null;
      };

      run = lib.mkOption {
        type = lib.types.nullOr (
          lib.types.enum [
            "always"
            "once"
            "when_changed"
          ]
        );
        description = "Specifies whether the task should run again or not if called more than once. Available options: `always`, `once` and `when_changed`.";
        defaultText = "always";
        default = null;
      };

      platforms = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        description = "Specifies which platforms the task should be run on.";
        default = [ ];
      };

      requires = lib.mkOption {
        type = (import ./requires_obj.nix) {inherit lib;};
        description = "A list of variables which should be set if this task is to run, if any of these variables are unset the task will error and not run.";
        default = { };
      };

      watch = lib.mkOption {
        type = lib.types.nullOr lib.types.bool;
        description = "Configures a task to run in watch mode automatically.";
        defaultText = "false";
        default = null;
      };
    };
  }
]
